# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a3f99e652a900eb7311c42ac4d34badf9fe32b1a588a586b2a495e8e549833917057ce00559c2a72c7db311fed736f4e060b25a705a2f90cf227f13af1609ab

test:
  secret_key_base: 904064ea443a9f0728e63fc087c361afe04c630a58cbd840027f446ffcbb5da64d6d1ae7a3b722401c24f81bb678d5d70cd8d5de4cacb11558072175fb1117b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
